# @package _global_

max_workers: 4
slides_dir: /mnt/data/MOU/mixed/RI_Scale

metadata:
  run_name: Build Dataset
  description: Scan slides directory and build slides.csv + patients.csv
  hyperparams:
    slides_dir: ${slides_dir}
