max_epochs: ${trainer.max_epochs}
log_every_n_steps: 1
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val/auroc
    mode: max
    save_top_k: 1
    filename: best
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val/auroc
    mode: max
    patience: ${trainer.patience}
